akhilnarang/scripts

- build-environment-setup.sh
> Update apt-get command

- build-environment-setup.sh
This is shorter, plus it forces a progress bar!
> Remove '-get' from apt-get

- arch-build-environment-setup.sh
These were the missing packages in my minimal Arch system. After adding them, script worked perfectly.
> scripts: arch: update needed dependencies

- install_android_sdk.bash
> Add Android SDK setup script

- arch-manjaro-apricity-build-environment-setup.sh
- linuxmint17x.sh
- ubuntu1404.sh
- ubuntu1604linuxmint18.sh
Also changed shebang on some scripts to se /usr/bin/env bash for
consistency and portability
> scripts : Install to /usr/local/bin/ rather than /usr/bin/

- github/change-default-branch.sh
> change-default-branch: Cleanup

- setup/android_build_env.sh
- setup/make.sh
> setup: make: Use axel to download

- setup/android-sdk-minimal.txt
- setup/install_android_sdk.bash
Uncommitted changes strike again
Fixes: 252aca688e07 ("setup: Android SDK installation improvements")
> setup: Fix derps in SDK install overhaul

- README.mkdn
> README: Fix Derp

- setup/android_build_env.sh
* Remove duplicate package and sort it by name
* Add curl package for Ubuntu 18
* Use openjdk-11-* instead
Signed-off-by: arizaini <famegalaxy614@gmail.com>
> setup/android_build_env: Small update

- rr/build.sh
Add link to failed builds
Add node name to finished message
Signed-off-by: mracar07 <umutcan@umutcanacar.me>
> RR: Update build script

- gerrit/parsepicks.py
Idk if I am opening this right but this will fix the github/create-repos script
> scripts: fix github create repo script

- setup/arch-manjaro.sh
Using sed to uncomment that repo, just incase n00bs like me forget to read that READMEME and blame you for non-working script
> setup: arch: Use sed to uncomment the multilib repo

- setup/android_build_env.sh
- Some TCs need libisl.so.15 which is provided by package libisl15
> android_env_setup: Also install libisl15

- setup/arch-manjaro.sh
useful
Signed-off-by: Simrat Singh <simrats169169@gmail.com>
> setup : Add patchelf

- setup/fedora.sh
* Add VIM for XXD hexdump tool required by brillo.
* Add virtual boot utilities for CGPT required by brillo.
* List packages vertically for easier viewing.
* Add license & short description of script and what it's
compatible with.
Change-Id: Id964aa8e3cc8bcc135be2aa0b7e19fca87f0fdb9
> Update Fedora for Android 10

- build-kernel
- release-kernel
- setup/android_build_env.sh
Tested on
* Ubuntu 20.04 Focal Fossa (development branch)
* Ubuntu 18.04 Bionic Beaver
Change-Id: Ic682bc0294cc3a6c5ad918e18a760d4d79a2a616
Signed-off-by: Akito Mizukito <akito@evolution-x.org>
> Added support for the upcoming Ubuntu 20.04 Focal Fossa & Fixed Github Actions

- setup/arch-manjaro.sh
* https://www.archlinux.org/packages/community/any/android-udev/
> arch-manjaro.sh: use the android-udev package instead

- setup/android_build_env.sh
- Used to github on server's like publishing releases etc
This closes #137 
Signed-off-by: Aayush Gupta <aayushgupta219@gmail.com>
> android_build_env: Install github's official cli package

- setup/android-sdk-minimal.txt
- setup/install_android_sdk.sh
...to current Android 11/12 available tools.
Also fix the script.
<3
Signed-off-by: Stefen Wakefield <me@xstefen.dev>
> setup/install_android_sdk: update packages and sync with upstream

- setup/arch-manjaro.sh
- Good to skip this in scripts.
> arch: Skip user confirmation to install

- setup/android_build_env.sh
Signed-off-by: Mohammad Hasan Keramat J <ikeramat@protonmail.com>
> setup: debian: Add support for Debian 11

- github/push-all-repos-git.sh
For lazy people like me who don't want to setup gerrit and still want to push all repos to github
> scripts: github: Add script to push all repos from manifest to github

- setup/fedora.sh
* Fedora 31 -> 36
Signed-off-by: Mohammad Hasan Keramat J <ikeramat@protonmail.com>
> setup: fedora: Add clang

- setup/android_build_env.sh
Just added the required if condition to let it work normally and add the otherwise missing packages.
> setup: android_build_env: Add support for PopOS

- setup/arch-manjaro.sh
Bare arch server setup doesn't have a font which throws this error while compling -https://katb.in/axoxiyibumo
> Arch env install font as well

- setup/crowdin-cli.sh
- Source -https://github.com/crowdin/crowdin-cli#installation
Change-Id: Id529f6840c3763ef5b9125f7107efaf1e996d78f
Signed-off-by: Sipun Ku Mahanta <sipunkumar85@gmail.com>
> scripts: setup: Revive crowdin cli installation script
