akhilnarang/scripts

release-kernel
- Ensure DERPVERSION is always provided
- Don't write an entire array into a string for changelog
=> release-kernel: Shellcheck cleanup and fixes

functions
Allows passing a Google Drive URL directly to start a download
with the gdrive utility, saving time spent manually slicing
the URL to retrieve the ID used by gdrive.
=> functions: Add gdrivedl

setup/android_build_env.sh
There's no reason to install this twice.
=> android_build_env.sh: remove duplicate build_essential package

setup/android_build_env.sh
* In an AOSP Build Environment, it's a good idea to install patchelf as it's commonly used while handling proprietary shared objects.
=> android_build_env: Install Patchelf

setup/android_build_env.sh
1. libncurses is not available for Ubuntu 18.10, we get the following error
while building:-
prebuilts/clang/host/linux-x86/clang-3289846/bin/clang.real: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
so, let's just symlink it.
2. ccache and ninja were always being installed (unnecessary overhead), lets only install it if any new version is available.
=> scripts: setup/android_build_env: add missing library for Ubuntu 18.10

README.mkdn
Since we use sed to uncomment the repo, the user doesn't need to even check the multilib
=> README: Need not instruct to enable multilib

setup/ccache.sh
Also includes tracking the necessary libs from the source instead of Ubuntu's outdated repos
Signed-off-by: Anirudh Gupta <anirudhgupta109@gmail.com>
=> setup: ccache: Track ccache from upstream

setup/arch-manjaro.sh
* Required to compile Android 10.
brillo_update_payload: line 342: xxd: command not found
I also ran into this problem on Solus, this can be solved by installing vim or putting xxd in path. Arch has a standalone package for it so lets just do that. I'll look into submitting a package to Solus.
=> setup: arch: Include xxd hexdump tool.

setup/android_build_env.sh
There is no point in doing if checks for version, if we don't update the version tag.
Our script will keep re-installing the same version over and over again!
=> setup/android_build_env.sh: update latest version of ccache and ninja

setup/arch-manjaro.sh
Included in aosp-devel now.
This reverts commit a1831f094a828caec94a3c762ae86311f4328311.
=> Revert "setup: arch: Include xxd hexdump tool. (#97)"

setup/android_build_env.sh
Setting up udev rules for adb!
sudo: curl: command not found
chmod: cannot access '/etc/udev/rules.d/51-android.rules': No such file or directory
chown: cannot access '/etc/udev/rules.d/51-android.rules': No such file or directory
* server not running *
adb: no process found
=> setup/android_build_env.sh: show deepin some lob

setup/android_build_env.sh
For distro hoppers, who mostly clone once, and its saved in some /home directory, after switching distro git credentials are lost and need to be re-added. Lets address this pain point too.
=> script: setup: Add support for git configuration

setup/android_build_env.sh, setup/arch-manjaro.sh, setup/fedora.sh, setup/solus.sh
For users who wants to compile gapps in-line ( such as Open Gapps) this package is necessary.
vendor/opengapps/build/config.mk:50: error: lzip decompressor not available.
Please install one first ("sudo apt-get install lunzip" or "sudo apt-get install lzip").
=> Add lzip package

setup/android_build_env.sh
- Also remove extraneous whitespace
=> android_env_setup: Avoid interactive prompts on apt install

setup/android_build_env.sh
Reverts akhilnarang/scripts#107
Package is not available on Ubuntu 19.10 ([packages.ubuntu.com](https://packages.ubuntu.com/search?keywords=libisl15&searchon=names))
=> For #108: Revert "android_env_setup: Also install libisl15"

setup/android_build_env.sh
Development branch, so full name. Will be changed once released
in April.
Also make sure lsb-core is installed so the check can complete
succesfully, as in some cases it doesn't exist on development
builds of Ubuntu.
=> Add Ubuntu 20.04 to LSB_RELEASE check.

setup/fedora.sh
I didn't catch this at first because I had Python 2 already on my system as another package's dependency.
=> Add Python 2 to Fedora setup script

setup/android_build_env.sh
* Latest debian iso already includes curl and rsync
* Since the buster release now already includes them it was removed from repository mirrors
which throws error when apt tries to install them and the script jumps to git setup section
skipping the entire package install list.
This patch fixes the install issue on buster and packages are installed.
Manually verified by compiling android after running this setup script with this patch included.
Signed-off-by: Harshit Jain <god@harsh1998.me>
=> scripts: drop buster packages

misc/extract_and_push.sh
- While dumping RMX2151 (using dumpyara of course), codename were empty.
Then I found out this new location can get the proper codename.
- _I will suggest for adding this patch to dumpyara too._
=> misc/extract_and_push.sh: Add another prop location for some oppo device's codename

misc/extract_and_push.sh
* Also move --no-check-certificate flag in wget before file to follow other commands syntax
=> extract_and_push: Don't check certificate for aria2c

misc/extract_and_push.sh
The following changes applies to realmeUI 2.0 updates
* Add props to properly detect brand & codename
* For brand detection we are actually using the same prop used by realme in their system apps
*  _ro.vendor.product.device.oem_ is the only prop to differentiate device variants
=> extract_and_push: Extract imgs from system/euclid (realme A11)

misc/extract_and_push.sh
* We want to know when there's an error, so just silence warnings
=> extract_and_push: Don't completely silence dtc

setup/fedora.sh
We need this package to access adb and fastboot.
Signed-off-by: Mohammad Hasan Keramat J <ikeramat80@gmail.com>
=> setup: fedora: Add android-tools package

setup/android_build_env.sh
adding GitHub packages repository.
Some env. don't have software-properties-common and scripts fails to run apt-add-repository command;
```
#bash android_build_env.sh
Adding GitHub apt key and repository!
Executing: /tmp/apt-key-gpghome.aXdgtXadYz/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
gpg: key C99B11DEB97541F0: "Nate Smith <vilmibm@github.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
sudo: apt-add-repository: command not found
=> setup: install software-properties-common before

setup/android_build_env.sh
Required to compile MTK libs and specifically preloader firmware
=> android_build_env: Install libswitch-perl as well

setup/android_build_env.sh
Fixed `gpg: keyserver receive failed: Server indicated a failure error` when `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0`
=> GPG keyserver error fix in `Update android_build_env.sh`

setup/android_build_env.sh
because why not
```
xstefen@leviathan:/mnt/c/Users/xstefen/git/scripts$ sudo apt-key adv --keyserver hkps://keyserver.ubuntu.com --recv-key C99B11DEB97541F0
[sudo] password for xstefen:
Executing: /tmp/apt-key-gpghome.ZFvTV0gXzL/gpg.1.sh --keyserver hkps://keyserver.ubuntu.com --recv-key C99B11DEB97541F0
gpg: key C99B11DEB97541F0: public key "Nate Smith <vilmibm@github.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```
=> android_build_env: upgrade to hkps for keyserver

setup/ccache.sh
Github recently removed support for unencrypted Git protocol.
Cloning with git:// protocol results in the following error,
```
Cloning into 'ccache'...
fatal: remote error:
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```
More details from [Github blog](https://github.blog/2021-09-01-improving-git-protocol-security-github/)
=> setup: ccache: Update SCM protocol to https

setup/android_build_env.sh
Ubuntu 22.04 LTS Jammy Jellyfish release is now available.
So extending focal packages to this version as well
=> setup: android_build_env: extend focal packages to jammy as well

setup/arch-manjaro.sh
Fixes the following:
perl: error while loading shared libraries: libcrypt.so.1: cannot open shared ob
ject file: No such file or directory
make[2]: *** [/home/pppig236/loss/kernel/xiaomi/sm6150/kernel/Makefile:135: kern
el/kheaders_data.tar.xz] Error 127
=> Add libxcrypt-compat for Arch env setup

setup/arch-manjaro.sh
* The package "libxcrypt-compat" is available in Archlinux core repository : https://archlinux.org/packages/core/x86_64/libxcrypt-compat Also it's getting installed by aosp-devel as a dependency : https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=aosp-devel&id=8cf0210389af8c1b082f746144e56930c9cf7cd8 Therefore if we clone it from aur and compile, it generates an older version of package and as we using --noconfirm option, it downgrades the package without asking. So let aosp-devel do the job of installing it.
Signed-off-by: Arrowsploit <arrowsploit@pm.me>
=> Arch-Androidenvsetup: Don't install libxcrypt-compat from AUR

setup/fedora.sh
Fixes
perl: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
on fedora rawhide
=> setup: fedora: Install libxcrypt-compat

setup/android_build_env.sh
* some custom roms require rsync in build, "error: rsync command not found", Installing this by default in the script fixes it
=> setup: Install rsync

setup/android_build_env.sh, setup/arch-manjaro.sh, setup/fedora.sh, setup/opensuse.sh
This is needed for Lineage's py extract utils
=> setup: Install pyelftools

setup/ccache.sh
* follow the official working method
current script yields the following error:
ccache.sh: line 6: ./autogen.sh: No such file or directory ccache.sh: line 7: ./configure: No such file or directory make: *** No targets specified and no makefile found.  Stop. [sudo] password for user: 
make: *** No rule to make target 'install'.  Stop. /tmp
autogen.sh no longer exists in the upstream repo
=> scripts: ccache: use cmake to configure build

setup/arch-manjaro.sh
If an aur helper (yay or paru) is installed, the packages will be installed using them. This allows for proper caching by the aur helpers.
=> Aur helpers
